### ISSUE TITLE
Servlet not working on Tomcat 7: TokenMgrError

### ISSUE THREAD

**Issue by chris922** [shred/shariff-backend-java#2]
There is a mistake in the ShariffServlet with the content type.

Inside the `doGet` the content type will be setted in a wrong way which results in the following exception (on Tomcat):

`org.apache.tomcat.util.http.parser.TokenMgrError: Lexical error at line 1, column 13.  Encountered: ":" (58), after : ""`

This is the line:

``` java
resp.setContentType("Content-type: application/json");
```

(see https://github.com/shred/shariff-backend-java/blob/v1.1/src/main/java/org/shredzone/shariff/ShariffServlet.java#L197)

The name of the header element ("Content-type") isn't required there and causes this `TokenMgrError`, so it just needs to be changed to:

``` java
resp.setContentType("application/json");
```

Anyway: Thanks for sharing this library, this saves us some time! :smiley: 

PS: To get this working I had to overwrite the `doGet`, but wasn't able to access the `backend` attribute, so maybe it's a good idea to add `setBackend`/`getBackend` (as `protected` should be enough) or change the visibility for `backend` to `protected`?

**Comment by shred** [comment]
Good catch! Thank you for reporting it! I have fixed it right now.

I also added a getBackend() method. However, a setBackend() method would confuse the cache, and I could not come up with a good use case for it.

I will publish a new version to maven central within in the next hours.

**Comment by chris922** [comment]
Wow, that was fast! Thank you very much!

And yes, `setBackend` wouldn't be such a good idea, but I supposed to have it to set the backend. But: You had a better idea and let `getBackend` call `createBackend`. :smiley: 

Best regards
