### ISSUE TITLE
Facebook Count

### ISSUE THREAD

**Issue by hagenah** [shred/shariff-backend-java#3]
The Facebook Target doesn't work. I tried
java -cp json.jar;shariff.jar org.shredzone.shariff.ShariffBackend http://www.example.com
and get

http://www.example.com
Aug 19, 2016 7:59:24 AM org.shredzone.shariff.ShariffBackend getCounts
WARNUNG: facebook @ http://www.example.com
java.lang.ClassCastException: org.json.JSONObject cannot be cast to org.json.JSONArray
        at org.shredzone.shariff.target.Facebook.extractCount(Facebook.java:29)
        at org.shredzone.shariff.target.JSONTarget.count(JSONTarget.java:42)
        at org.shredzone.shariff.ShariffBackend$2.call(ShariffBackend.java:151)
        at org.shredzone.shariff.ShariffBackend$2.call(ShariffBackend.java:148)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

I looked in the source code and tried
https://api.facebook.com/method/fql.query?format=json&query=select%20share_count%20from%20link_stat%20where%20url=%22http%3A%2F%2Fwww.example.com%22
and get
{"error_code":12,"error_msg":"REST API is deprecated for versions v2.1 and higher (12)","request_args":[{"key":"method","value":"fql.query"},{"key":"format","value":"json"},{"key":"query","value":"select share_count from link_stat where url=\"http:\/\/www.example.com\""}]}

**Comment by shred** [comment]
Thank you for the report! It seems that Facebook deprecated the fql API. I will fix it...

**Comment by shred** [comment]
The current master branch contains a fix for the Facebook counter.

Unfortunately, Facebook now seems to require an access token, which in turn needs an application ID and application secret, which in turn needs a Facebook account. I don't have a Facebook account (and I don't want to have one), so I could only validate my fix with unit tests.

Do you have a way to test the current master branch against a real Facebook account? I would appreciate your feedback.

**Comment by shred** [comment]
By the way, you can test it like this:

java -cp json.jar;shariff.jar -Dfacebook.id=yourId -Dfacebook.secret=yourSecret org.shredzone.shariff.ShariffBackend http://www.example.com

**Comment by hagenah** [comment]
I have to create a facebook account, too. I'm on holiday at the moment and will do it when I'm back at the office.

**Comment by hagenah** [comment]
It works if the share count is not zero :-). If it's zero than the share key is missing. Something like
`    protected int extractCount(JSONObject json) throws JSONException {`
`        if(json.has("id") && !json.has("share"))`
`            return 0;`
`        else`
`            return json.getJSONObject("share").getInt("share_count");`
`    }`
works.

**Comment by shred** [comment]
Thank you for your help! I fixed that problem and will release a new version in the next hours.
